# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Feel at home in your local pub
email: your-email@example.com
description:  Your local is about proper pubs, the perfect place to meet friends, dine with the family or just a home from home with great beers. 
author:  Design & Develpment by James Goldsworthy for Punch
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ourlocal.pub" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OurLocalPub
instagram_username: OurLocalPub

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

plugins:
 - jekyll-paginate-v2


# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- config.codekit3
- assets/raw


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# 
# 
# collections:
#   pub:
#     output: true
#   about:
#     output: true
#       
#  
# 
# defaults:
#   - scope:
#       type: pub
#     values:
#      layout: htmlbasepubmain2
# 
#   - scope:
#       type: about
#     values:
#      layout: htmlbasepub2    